spring.application.name=loja
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:h2:file:./dados/loja
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=SA
spring.datasource.password=
spring.sql.init.mode=always